var Products=[
    {id:1,price:15000,description:'good quality super performed',brand:'mi',image:'images/electronics/phone 1.jpg',catagery:'electronics',name:'phone',rating:4.2},
    {id:2,price:15000,description:'good quality super performed',brand:'mi',image:'images/electronics/phone 2.jpg',catagery:'electronics',name:'phone',rating:4.2},
    {id:3,price:25000,description:'good quality super performed',brand:'mi',image:'images/electronics/download (1).jpg',catagery:'electronics',name:'phone',rating:4.2},
    {id:4,price:10000,description:'good quality super performed',brand:'samsung',image:'images/electronics/download (2).jpg',catagery:'electronics',name:'phone',rating:4.2},
    {id:5,price:12000,description:'good quality super performed',brand:'samsung',image:'images/electronics/download (3).jpg',catagery:'electronics',name:'phone',rating:4.2},
    {id:6,price:15000,description:'good quality super performed',brand:'vivo',image:'images/electronics/download (5).jpg',catagery:'electronics',name:'phone',rating:4.2},
    {id:7,price:15000,description:'good quality super performed',brand:'vivo',image:'images/electronics/download (6).jpg',catagery:'electronics',name:'phone',rating:4.2},
    {id:8,price:25000,description:'good quality super performed',brand:'vivo',image:'images/electronics/download (7).jpg',catagery:'electronics',name:'phone',rating:4.2},
    {id:9,price:35000,description:'good quality super performed',brand:'vivo',image:'images/electronics/download (8).jpg',catagery:'electronics',name:'phone',rating:4.2},
    {id:10,price:35000,description:'good quality super performed',brand:'redmi',image:'images/electronics/download (8).jpg',catagery:'electronics',name:'phone',rating:4.2},
    {id:11,price:15000,description:'good quality super performed',brand:'redmi',image:'images/electronics/phone 1.jpg',catagery:'electronics',name:'phone',rating:4.2},
    {id:12,price:15000,description:'good quality super performed',brand:'redmi',image:'images/electronics/phone 2.jpg',catagery:'electronics',name:'phone',rating:4.2},

    {id:13,price:3000,description:'good quality super performed',brand:'boat',image:'images/electronics/download (9).jpg',catagery:'electronics',name:'earbuds',rating:4.2},
    {id:14,price:5000,description:'good quality super performed',brand:'boat',image:'images/electronics/download (10).jpg',catagery:'electronics',name:'earbuds',rating:4.2},
    {id:15,price:5000,description:'good quality super performed',brand:'boat',image:'images/electronics/download (10).jpg',catagery:'electronics',name:'earbuds',rating:4.2},
    {id:16,price:1000,description:'good quality super performed',brand:'boat',image:'images/electronics/download (11).jpg',catagery:'electronics',name:'earbuds',rating:4.2},
    {id:17,price:2000,description:'good quality super performed',brand:'truck',image:'images/electronics/download (12).jpg',catagery:'electronics',name:'earbuds',rating:4.2},
    {id:18,price:2000,description:'good quality super performed',brand:'truck',image:'images/electronics/download (13).jpg',catagery:'electronics',name:'earbuds',rating:4.2},
    {id:19,price:1000,description:'good quality super performed',brand:'truck',image:'images/electronics/download (14).jpg',catagery:'electronics',name:'earbuds',rating:4.2},
    {id:20,price:2000,description:'good quality super performed',brand:'truck',image:'images/electronics/download (9).jpg',catagery:'electronics',name:'earbuds',rating:4.2},
    {id:21,price:3000,description:'good quality super performed',brand:'boult',image:'images/electronics/download (13).jpg',catagery:'electronics',name:'earbuds',rating:4.2},
    {id:22,price:4000,description:'good quality super performed',brand:'boult',image:'images/electronics/images.jpg',catagery:'electronics',name:'earbuds',rating:4.2},
    {id:23,price:5000,description:'good quality super performed',brand:'boult',image:'images/electronics/images (2).jpg',catagery:'electronics',name:'earbuds',rating:4.2},
    {id:24,price:1200,description:'good quality super performed',brand:'boult',image:'images/electronics/images (3).jpg',catagery:'electronics',name:'earbuds',rating:4.2},
    {id:25,price:1500,description:'good quality super performed',brand:'boat',image:'images/electronics/images.jpg',catagery:'electronics',name:'earbuds',rating:4.2},
    
    {id:26,price:60000,description:'good quality super performed',brand:'dell',image:'images/electronics/laptap1.jpg',catagery:'electronics',name:'laptap',rating:4.2},
    {id:27,price:70000,description:'good quality super performed',brand:'dell',image:'images/electronics/laptap (2).jpg',catagery:'electronics',name:'laptap',rating:4.2},
    {id:28,price:55000,description:'good quality super performed',brand:'hp',image:'images/electronics/laptap (3).jpg',catagery:'electronics',name:'laptap',rating:4.2},
    {id:29,price:95000,description:'good quality super performed',brand:'hp',image:'images/electronics/laptap (4).jpg',catagery:'electronics',name:'laptap',rating:4.2},
    {id:30,price:80000,description:'good quality super performed',brand:'hp',image:'images/electronics/laptap (5).jpg',catagery:'electronics',name:'laptap',rating:4.2},
    {id:31,price:100000,description:'good quality super performed',brand:'lenova',image:'images/electronics/laptap1.jpg',catagery:'electronics',name:'laptap',rating:4.2},
    {id:32,price:100000,description:'good quality super performed',brand:'lenova',image:'images/electronics/laptap (3).jpg',catagery:'electronics',name:'laptap',rating:4.2},

    {id:33,price:10000,description:'good quality super performed',brand:'sony',image:'images/electronics/images (4).jpg',catagery:'electronics',name:'tv',rating:4.2},
    {id:34,price:12000,description:'good quality super performed',brand:'sony',image:'images/electronics/images (5).jpg',catagery:'electronics',name:'tv',rating:4.2},
    {id:35,price:10000,description:'good quality super performed',brand:'sony',image:'images/electronics/images (6).jpg',catagery:'electronics',name:'tv',rating:4.2},
    {id:36,price:120000,description:'good quality super performed',brand:'lg',image:'images/electronics/images (7).jpg',catagery:'electronics',name:'tv',rating:4.2},
    {id:37,price:200000,description:'good quality super performed',brand:'lg',image:'images/electronics/images (8).jpg',catagery:'electronics',name:'tv',rating:4.2},
    {id:38,price:260000,description:'good quality super performed',brand:'lg',image:'images/electronics/images (9).jpg',catagery:'electronics',name:'tv',rating:4.2},
    {id:39,price:100000,description:'good quality super performed',brand:'sony',image:'images/electronics/download (21).jpg',catagery:'electronics',name:'tv',rating:4.2},
    {id:40,price:270000,description:'good quality super performed',brand:'samsung',image:'images/electronics/images (10).jpg',catagery:'electronics',name:'tv',rating:4.2},
    {id:41,price:30000,description:'good quality super performed',brand:'samsung',image:'images/electronics/images (11).jpg',catagery:'electronics',name:'tv',rating:4.2},
    {id:42,price:20000,description:'good quality super performed',brand:'samsung',image:'images/electronics/images (12).jpg',catagery:'electronics',name:'tv',rating:4.2},
    {id:43,price:35000,description:'good quality super performed',brand:'lg',image:'images/electronics/images (13).jpg',catagery:'electronics',name:'tv',rating:4.2},
    {id:44,price:10000,description:'good quality super performed',brand:'samsung',image:'images/electronics/images (14).jpg',catagery:'electronics',name:'tv',rating:4.2},

    {id:45,price:3000,description:'good quality super performed',brand:'firebult',image:'images/electronics/download (21).jpg',catagery:'electronics',name:'smartwatch',rating:4.2},
    {id:46,price:4000,description:'good quality super performed',brand:'firebult',image:'images/electronics/download (22).jpg',catagery:'electronics',name:'smartwatch',rating:4.2},
    {id:47,price:3500,description:'good quality super performed',brand:'firebult',image:'images/electronics/download (23).jpg',catagery:'electronics',name:'smartwatch',rating:4.2},
    {id:48,price:4000,description:'good quality super performed',brand:'apple',image:'images/electronics/download (24).jpg',catagery:'electronics',name:'smartwatch',rating:4.2},
    {id:49,price:4500,description:'good quality super performed',brand:'apple',image:'images/electronics/download (25).jpg',catagery:'electronics',name:'smartwatch',rating:4.2},
    {id:50,price:5000,description:'good quality super performed',brand:'apple',image:'images/electronics/download (26).jpg',catagery:'electronics',name:'smartwatch',rating:4.2},
    {id:51,price:2000,description:'good quality super performed',brand:'bgr',image:'images/electronics/download (27).jpg',catagery:'electronics',name:'smartwatch',rating:4.2},
    {id:52,price:1000,description:'good quality super performed',brand:'bgr',image:'images/electronics/download (28).jpg',catagery:'electronics',name:'smartwatch',rating:4.2},
    {id:53,price:1500,description:'good quality super performed',brand:'bgr',image:'images/electronics/download (29).jpg',catagery:'electronics',name:'smartwatch',rating:4.2},
    {id:54,price:4000,description:'good quality super performed',brand:'firebult',image:'images/electronics/download (30).jpg',catagery:'electronics',name:'smartwatch',rating:4.2},

    {id:55,price:400,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (1).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:56,price:500,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (2).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:57,price:600,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (3).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:58,price:700,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (4).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:59,price:800,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (5).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:60,price:900,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (6).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:61,price:1000,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (7).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:62,price:1200,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (8).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:63,price:1400,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (9).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:64,price:1400,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (10).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:65,price:1200,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (11).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:66,price:400,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (12).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:67,price:800,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (13).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:68,price:900,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (14).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:69,price:1000,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (15).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:70,price:500,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (16).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:71,price:600,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (17).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:72,price:700,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (18).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:73,price:300,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (19).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:74,price:400,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (20).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:75,price:500,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (21).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:76,price:600,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (22).webp',catagery:'fashion',name:'dress',rating:4.2},
    {id:77,price:800,description:'good quality soft and contton',brand:'trends',image:'images/fashion/shopping (23).webp',catagery:'fashion',name:'dress',rating:4.2},
   
    {id:78,price:40000,description:'pure gold excelent digines',brand:' gold',image:'images/fashion/shopping (24).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:79,price:10400,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (25).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:80,price:140000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (26).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:81,price:40000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (27).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:82,price:45000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (28).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:83,price:46000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (29).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:84,price:70000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (30).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:85,price:80000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (31).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:86,price:90000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (32).webp',catagery:'fashion',name:'jewellary',rating:4.2},
   {id:87,price:80000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (33).webp',catagery:'fashion',name:'jewellary',rating:4.2},
   {id:88,price:14000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (34).webp',catagery:'fashion',name:'jewellary',rating:4.2},
   {id:89,price:14000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (34).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:90,price:180000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (35).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:91,price:90000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (36).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:92,price:50000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (37).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:93,price:45000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (38).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:94,price:60000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (39).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:95,price:70000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (40).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:96,price:80000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (41).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:97,price:90000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (42).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:98,price:100000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (43).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:99,price:40000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (44).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:100,price:140000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (45).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:101,price:150000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (46).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:102,price:40000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (47).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:103,price:50000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (48).webp',catagery:'fashion',name:'jewellary',rating:4.2},
    {id:104,price:60000,description:'pure gold excelent digines',brand:'gold',image:'images/fashion/shopping (49).webp',catagery:'fashion',name:'jewellary',rating:4.2},
   
    {id:105,price:400,description:'if will be protech over skin and super fresh',brand:'lakme',image:'images/fashion/shopping (50).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:106,price:200,description:'if will be protech over skin and super fresh',brand:'lakme',image:'images/fashion/shopping (51).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:107,price:300,description:'if will be protech over skin and super fresh',brand:'lakme',image:'images/fashion/shopping (52).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:108,price:100,description:'if will be protech over skin and super fresh',brand:'lakme',image:'images/fashion/shopping (53).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:109,price:400,description:'if will be protech over skin and super fresh',brand:'lakme',image:'images/fashion/shopping (54).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:110,price:500,description:'if will be protech over skin and super fresh',brand:'lakme',image:'images/fashion/shopping (55).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:111,price:600,description:'if will be protech over skin and super fresh',brand:'lakme',image:'images/fashion/shopping (56).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:112,price:700,description:'if will be protech over skin and super fresh',brand:'lakme',image:'images/fashion/shopping (56).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:113,price:800,description:'if will be protech over skin and super fresh',brand:'lakme',image:'images/fashion/shopping (56).webp',catagery:'beauty',name:'cosmoticy',rating:4.2},
     {id:114,price:900,description:'if will be protech over skin and super fresh',brand:'lakme',image:'images/fashion/shopping (57).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:115,price:300,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (58).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
    {id:116,price:100,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (57).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:117,price:120,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (58).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:118,price:600,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (60).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:119,price:500,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (61).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
   {id:120,price:700,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (62).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
    {id:121,price:800,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (63).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:122,price:500,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (64).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:123,price:300,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (65).webp',catagery:'beauty',name:'cosmotic',rating:4.2},
    {id:124,price:400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (66).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
    {id:125,price:400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (67).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
    {id:126,price:400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (68).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
    {id:127,price:400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (69).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
 {id:128,price:400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (70).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
 {id:129,price:400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (71).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
 {id:130,price:400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (72).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
 {id:131,price:400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (73).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
 {id:132,price:400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (74).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
 {id:133,price:400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (75).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
 {id:134,price:400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (76).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
 {id:135,price:400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (77).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
 {id:136,price:400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (78).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
 {id:137,price:800,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (79).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
 {id:138,price:600,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (80).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
 {id:139,price:1400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (81).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
 {id:140,price:2400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (82).webp',catagery:'beauty',name:'cosmotic',rating:4.2}, 
 {id:141,price:8400,description:'if will be protech over skin and super fresh',brand:'mamaearth',image:'images/fashion/shopping (82).webp',catagery:'beauty',name:'cosmotic',rating:4.8} ,
 
 {id:142,price:800,description:'super quality looking beauty',brand:'farnitur',image:'images/fashion/k1.webp',catagery:'kichen',name:'kichen item',rating:4.8}, 
 {id:143,price:400,description:'super quality looking beauty',brand:'farnitur',image:'images/fashion/k2.jpg',catagery:'kichen',name:'kichen item',rating:4.8}, 
 {id:144,price:500,description:'super quality looking beauty',brand:'farnitur',image:'images/fashion/k3.webp',catagery:'kichen',name:'kichen item',rating:4.8}, 
 {id:145,price:600,description:'super quality looking beauty',brand:'farnitur',image:'images/fashion/k4.webp',catagery:'kichen',name:'kichen item',rating:4.8}, 
 {id:146,price:700,description:'super quality looking beauty',brand:'farnitur',image:'images/fashion/k5.webp',catagery:'kichen',name:'kichen item',rating:4.8}, 
 {id:147,price:800,description:'super quality looking beauty',brand:'farnitur',image:'images/fashion/k6.webp',catagery:'kichen',name:'kichen item',rating:4.8}, 
 {id:148,price:900,description:'super quality looking beauty',brand:'farnitur',image:'images/fashion/k7.webp',catagery:'kichen',name:'kichen item',rating:4.8}, 
 {id:149,price:500,description:'super quality looking beauty',brand:'farnitur',image:'images/fashion/k8.webp',catagery:'kichen',name:'kichen item',rating:4.8}, 
 {id:150,price:700,description:'super quality looking beauty',brand:'farnitur',image:'images/fashion/k9.webp',catagery:'kichen',name:'kichen item',rating:4.8}, 


]
export default Products;